import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MobXProvider } from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[url('/sunny.jpg')] px-12 py-12 h-screen w-screen">
        <div className="bg-zinc-900 h-full w-full rounded-2xl shadow-black  shadow-2xl p-7 ">
          {children}
        </div>
      </body>
    </html>
  );
}
